INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('B_SMART', 'COMPRAS',7000.0, 14999.0, 18, 23);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('AFINITY_CARD', 'COMPRAS',7000.0, 14999.0, 18, 23);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('B_SMART', 'COMPRAS',7000.0, 14999.0, 24, 32);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('CLASICA', 'COMPRAS',7000.0, 14999.0, 24, 32);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('AFINITY_CARD', 'COMPRAS',7000.0, 14999.0, 24, 32);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('OFFICE_DEPOT', 'COMPRAS',7000.0, 14999.0, 24, 32);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('COSTCO', 'COMPRAS',7000.0, 14999.0, 24, 32);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('BEST_BUY_BANAMEX', 'COMPRAS',7000.0, 14999.0, 24, 32);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('THE_HOME_DEPOT', 'COMPRAS',7000.0, 14999.0, 24, 32);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('CLASICA', 'COMPRAS',7000.0, 14999.0, 33, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('OFFICE_DEPOT', 'COMPRAS',7000.0, 14999.0, 33, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('COSTCO', 'COMPRAS',7000.0, 14999.0, 33, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('BEST_BUY_BANAMEX', 'COMPRAS',7000.0, 14999.0, 33, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('THE_HOME_DEPOT', 'COMPRAS',7000.0, 14999.0, 33, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('B_SMART', 'COMPRAS',15000.0, 34999.0, 18, 23);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('AFINITY_CARD', 'COMPRAS',15000.0, 34999.0, 18, 23);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('ORO', 'COMPRAS',15000.0, 34999.0, 24, 32);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('AFINITY_CARD', 'COMPRAS',15000.0, 34999.0, 24, 32);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('OFFICE_DEPOT', 'COMPRAS',15000.0, 34999.0, 24, 32);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('COSTCO', 'COMPRAS',15000.0, 34999.0, 24, 32);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('BEST_BUY_BANAMEX', 'COMPRAS',15000.0, 34999.0, 24, 32);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('THE_HOME_DEPOT', 'COMPRAS',15000.0, 34999.0, 24, 32);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('ORO', 'COMPRAS',15000.0, 34999.0, 33, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('OFFICE_DEPOT', 'COMPRAS',15000.0, 34999.0, 33, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('COSTCO', 'COMPRAS',15000.0, 34999.0, 33, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('BEST_BUY_BANAMEX', 'COMPRAS',15000.0, 34999.0, 33, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('THE_HOME_DEPOT', 'COMPRAS',15000.0, 34999.0, 33, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('B_SMART', 'COMPRAS', 35000.0, 49999.0, 18, 23);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('AFINITY_CARD', 'COMPRAS', 35000.0, 49999.0, 18, 23);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('PLATINUM', 'COMPRAS',35000.0, 49999.0, 24, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('OFFICE_DEPOT', 'COMPRAS',35000.0, 49999.0, 24, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('COSTCO', 'COMPRAS',35000.0, 49999.0, 24, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('BEST_BUY_BANAMEX', 'COMPRAS',35000.0, 49999.0, 24, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('THE_HOME_DEPOT', 'COMPRAS',35000.0, 49999.0, 24, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('B_SMART', 'COMPRAS', 50000.0, 5000000.0, 18, 23);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('AFINITY_CARD', 'COMPRAS', 50000.0, 5000000.0, 18, 23);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('PLATINUM', 'COMPRAS',50000.0, 5000000.0, 24, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('CITI_AADVANTAGE', 'VIAJES', 12000.0, 29999.0, 18, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('CITI_AADVANTAGE', 'VIAJES', 30000.0, 34999.0, 18, 23);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('CITI_AADVANTAGE', 'VIAJES', 30000.0, 34999.0, 24, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('PLATINUM', 'VIAJES', 30000.0, 34999.0, 24, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('CITI_AADVANTAGE', 'VIAJES', 35000.0, 49999.0, 18, 23);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('CITI_AADVANTAGE', 'VIAJES', 35000.0, 49999.0, 24, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('PLATINUM', 'VIAJES', 35000.0, 49999.0, 24, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('CITI_AADVANTAGE', 'VIAJES', 50000.0, 5000000.0, 18, 22);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('PLATINUM', 'VIAJES', 50000.0, 5000000.0, 23, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('BANAMEX_TELETON', 'CARIDAD', 12000.0, 5000000.0, 18, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('APAC', 'CARIDAD', 12000.0, 5000000.0, 18, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('OFFICE_DEPOT', 'NEGOCIOS', 7000.0, 5000000.0, 18, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('COSTCO', 'NEGOCIOS', 7000.0, 5000000.0, 18, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('BEST_BUY_BANAMEX', 'NEGOCIOS', 7000.0, 5000000.0, 18, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('THE_HOME_DEPOT', 'NEGOCIOS', 7000.0, 5000000.0, 18, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('MARTI_CLASICA_CITIBANAMEX', 'DEPORTES', 7000.0, 34999.0, 18, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('AMERICA_DEPORTEISMO', 'DEPORTES', 7000.0, 34999.0, 18, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('PUMAS_DEPORTEISMO', 'DEPORTES', 7000.0, 34999.0, 18, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('TOLUCA_DEPORTEISMO', 'DEPORTES', 7000.0, 34999.0, 18, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('LA_VERDE_DEPORTEISMO', 'DEPORTES', 7000.0, 34999.0, 18, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('MARTI_PREMIUM_CITIBANAMEX', 'DEPORTES', 35000.0, 5000000.0, 18, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('B_SMART', 'ESTILO', 7000.0, 14999.0, 18, 32);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('AFINITY_CARD', 'ESTILO', 7000.0, 14999.0, 18, 32);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('B_SMART', 'ESTILO', 7000.0, 14999.0, 33, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('B_SMART', 'ESTILO', 15000.0, 29999.0, 18, 23);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('AFINITY_CARD', 'ESTILO', 15000.0, 29999.0, 18, 23);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('B_SMART', 'ESTILO', 15000.0, 29999.0, 24, 32);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('ORO', 'ESTILO', 15000.0, 29999.0, 24, 32);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('AFINITY_CARD', 'ESTILO', 15000.0, 29999.0, 24, 32);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('ORO', 'ESTILO', 15000.0, 29999.0, 33, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('B_SMART', 'ESTILO', 30000.0, 34999.0, 18, 23);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('AFINITY_CARD', 'ESTILO', 30000.0, 34999.0, 18, 23);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('B_SMART', 'ESTILO', 30000.0, 34999.0, 24, 32);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('PLATINUM', 'ESTILO', 30000.0, 34999.0, 24, 32);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('AFINITY_CARD', 'ESTILO', 30000.0, 34999.0, 24, 32);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('PLATINUM', 'ESTILO', 30000.0, 34999.0, 33, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('B_SMART', 'ESTILO', 35000.0, 5000000.0, 18, 23);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('B_SMART', 'ESTILO', 35000.0, 5000000.0, 24, 75);
INSERT INTO tarjetas.tarjetas (nombre_tarjeta, preferencias, salario_minimo, salario_maximo, edad_minima, edad_maxima) VALUES('PLATINUM', 'ESTILO', 35000.0, 5000000.0, 24, 75);