package com.ibm.academia.tarjetas.enums;

public enum NombreTarjetas 
{
	B_SMART,
	AFINITY_CARD,
	CLASICA,
	OFFICE_DEPOT,
	COSTCO,
	BEST_BUY_BANAMEX,
	THE_HOME_DEPOT,
	ORO,
	PLATINUM,
	CITI_AADVANTAGE,
	BANAMEX_TELETON,
	APAC,
	MARTI_CLASICA_CITIBANAMEX,
	AMERICA_DEPORTEISMO,
	PUMAS_DEPORTEISMO,
	TOLUCA_DEPORTEISMO,
	LA_VERDE_DEPORTEISMO,
	MARTI_PREMIUM_CITIBANAMEX,

}
